#
#  cfg.mk
#

RAM_BASE  = 0x04020000
STACK_SIZE = 0x1000
BOOTROM_BSS_SIZE = 0xa00
PUBLIC_KEY_SIZE = 0x1000
TEE_KEY_SIZE = 0x100
TP_KEY_SIZE = 0x100
GSL_INFO_SIZE = 0x200
#CFG_DEBUG_INFO = 1
TEXT_OFST= $(STACK_SIZE) + $(BOOTROM_BSS_SIZE) + $(PUBLIC_KEY_SIZE) + $(TEE_KEY_SIZE) + $(TP_KEY_SIZE) + $(GSL_INFO_SIZE)
TEXT_BASE = $(shell printf "0x%x" $$(($(RAM_BASE) + $(TEXT_OFST))))
